### ISSUE TITLE
Any experiment result that can conclude the sentence piece Japanese BERT model outperforms word piece one?

### ISSUE THREAD

**Issue by weiczhu** [yoheikikuta/bert-japanese#8]
Do we have any result to support that the sentence piece is better?

**Comment by yoheikikuta** [comment]
(I assume word piece you mention here is the word piece tokenizer used in the original BERT repository.)

Although I don't know a perfect comparison between them, I strongly believe BERT with SentencePiece is better.

The reasons are as follows:
- The word piece tokenizer is completely depending on the white space tokenization which is obviously not for Japanese text (the word piece tokenizer almost acts as a character-by-character one). Of course, this is not absolute since sometimes a character based tokenizer is better.
- Previously I compared BERT with SentencePiece with BERT with WordPiece (precisely, the pre-trained multilingual BERT model provide by the original BERT repository). The former is clearly better (sorry this blog post in Japanese): https://techlife.cookpad.com/entry/2018/12/04/093000.

**Comment by weiczhu** [comment]
Got it! Thank you very much for your explanation. We are now also experimenting the sentence piece on the Japanese corpus. We will also update the result and hear your comments. Thank you!
